version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: barangay_app_prod
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - app_data:/var/www
    networks:
      - barangay_network_prod

  nginx:
    image: nginx:alpine
    container_name: barangay_nginx_prod
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - app_data:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - barangay_network_prod

volumes:
  app_data:

networks:
  barangay_network_prod:
    driver: bridge
